---
- name: Configure New User and Packages
  hosts: all
  become: true

  vars:
    new_user: john
    new_user_home: /better-place/{{ new_user }}
    new_user_id: 1234

  tasks:
    - name: Create new user
      user:
        name: "{{ new_user }}"
        home: "{{ new_user_home }}"
        uid: "{{ new_user_id }}"
        create_home: true

    - name: Configure sudo access without password prompt
      lineinfile:
        dest: /etc/sudoers
        line: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

    - name: Copy nice-script.sh to user's home directory
      copy:
        src: nice-script.sh
        dest: "{{ new_user_home }}/nice-script.sh"
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: "0755"

    - name: List mounted filesystems
      command: "{{ new_user_home }}/nice-script.sh"
      register: filesystems_output

    - name: Display the output
      debug:
        var: filesystems_output.stdout_lines

    - name: Install Tmux and Vim packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - tmux
        - vim

    - name: Install Terraform CLI
      become_user: "{{ new_user }}"
      shell: |
        curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
        unzip terraform_1.0.0_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
      args:
        chdir: "{{ new_user_home }}"
